version: '3.9'
name: 'rinha-giovannibassi-2'

services:
  api1: &api
    build:
      context: .
      dockerfile: Dockerfile
    image: giggio/rinhabackend-2401:rust
    hostname: api1
    container_name: rinhaapi1
    environment:
      - CONNECTION_STRING=postgres://rinha:rinha@db:5432/rinha
    depends_on:
      db:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '80MB'
    networks:
      - app-network

  api2:
    <<: *api
    hostname: api2
    container_name: rinhaapi2

  envoy:
    image: envoyproxy/envoy:v1.29-latest
    container_name: rinhaproxy
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '134MB'

  db:
    image: postgres:latest
    container_name: rinhadb
    command: 'postgres -c max_connections=300 -c shared_buffers=96MB -c checkpoint_timeout=600 -c synchronous_commit=off -c fsync=off -c full_page_writes=off -c work_mem=16MB'
    hostname: db
    environment:
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_USER=rinha
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./sql/ddl.sql:/docker-entrypoint-initdb.d/01-ddl.sql:ro
      - ./sql/criartransacao.sql:/docker-entrypoint-initdb.d/11-criartransacao.sql:ro
      - ./sql/resetdb.sql:/docker-entrypoint-initdb.d/21-resetdb.sql:ro
      - type: tmpfs
        target: /var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '256MB'
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "pg_isready", "--username", "rinha"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

networks:
  app-network:

